apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-a-workloads
  namespace: argocd
  labels:
    tenant_id: tenant-a
spec:
  project: tenant-a

  source:
    repoURL: https://github.com/nguyenha0112/Self_Heal_AgentAWS.git
    targetRevision: HEAD
    path: manifests/workloads
    directory:
      include: "{tenant-a-sample-app.yaml,ecommerce-api-tenant-a.yaml,ecommerce-web-tenant-a.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-a

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
