---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cdo-ecommerce-demo
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: cdo-ecommerce-demo
    role: app-metrics
spec:
  selector:
    matchLabels:
      tier: cdo-ecommerce-demo
      service: ecommerce-api
  namespaceSelector:
    matchNames:
      - tenant-a
      - tenant-b
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: false
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app]
          targetLabel: deployment
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_label_service]
          targetLabel: service
        - sourceLabels: [__meta_kubernetes_service_label_tenant]
          targetLabel: tenant
